base_path: data/runs/training
description: Cartpole
env_name: CartPole-v1
logging:
  checkpoint_freq: 127800
  video_freq: 127800
reward:
  alpha: 0.5
  baseline_prompts:
  - pole and cart
  batch_size: 120 # batch size 120 = 120/30 = 4 seconds 
  # batch_size: 80
  cache_dir: data/cache
  camera_config:
    azimuth: 180.0
    distance: 3.5
    elevation: -10.0
    lookat:
    - 0.0
    - 0.0
    - 1.0
    trackbodyid: 1
  name: clip
  pretrained_model: ViT-bigG-14/laion2b_s39b_b160k
  target_prompts:
  - pole vertically upright on top of the cart
rl:
  batch_size: 256
  episode_length: 360
  gamma: 0.9999
  gradient_steps: 1
  learning_rate: 0.0023
  learning_starts: 75000
  n_envs_per_worker: 4
  n_steps: 3000000
  policy_name: MlpPolicy
  tau: 0.01
  train_freq: 360
seed: 42
tags:
- clip
- sofa_env
- deflect_spheres
